apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: microk8s-gcp
  namespace: default
spec:
  clusterNetwork:
    apiServerPort: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: MicroK8sControlPlane
    name: microk8s-gcp-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPCluster
    name: microk8s-gcp
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPCluster
metadata:
  name: microk8s-gcp
  namespace: default
spec:
  network:
    name: default
  project: sachin-singh-gce-account
  region: europe-west1
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: MicroK8sControlPlane
metadata:
  name: microk8s-gcp-control-plane
  namespace: default
spec:
  controlPlaneConfig:
    clusterConfiguration:
      portCompatibilityRemap: true
    initConfiguration:
      IPinIP: true
      addons:
      - dns
      - ingress
      joinTokenTTLInSecs: 900000
  machineTemplate:
    infrastructureTemplate:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: GCPMachineTemplate
      name: microk8s-gcp-control-plane
  replicas: 3
  upgradeStrategy: SmartUpgrade
  version: v1.25.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: microk8s-gcp-control-plane
  namespace: default
spec:
  template:
    spec:
      image: projects/sachin-singh-gce-account/global/images/ubuntu-2204
      instanceType: n1-standard-2
      publicIP: true
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: microk8s-gcp-md-0
  namespace: default
spec:
  clusterName: microk8s-gcp
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: MicroK8sConfigTemplate
          name: microk8s-gcp-md-0
      clusterName: microk8s-gcp
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPMachineTemplate
        name: microk8s-gcp-md-0
      version: 1.25.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: microk8s-gcp-md-0
  namespace: default
spec:
  template:
    spec:
      image: projects/sachin-singh-gce-account/global/images/ubuntu-2204
      instanceType: n1-standard-2
      publicIP: true
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: MicroK8sConfigTemplate
metadata:
  name: microk8s-gcp-md-0
  namespace: default
spec:
  template:
    spec:
      clusterConfiguration:
        portCompatibilityRemap: true
